// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'AlertInfo': typeof import("../components/Alert/AlertInfo.vue")['default'],
    'AlertBorderLeft': typeof import("../components/Alert/BorderLeft.vue")['default'],
    'AlertDefaultAlert': typeof import("../components/Alert/DefaultAlert.vue")['default'],
    'AlertStateAlert': typeof import("../components/Alert/StateAlert.vue")['default'],
    'AlertWithBorder': typeof import("../components/Alert/WithBorder.vue")['default'],
    'AlertWithButton': typeof import("../components/Alert/WithButton.vue")['default'],
    'AlertWithIcon': typeof import("../components/Alert/WithIcon.vue")['default'],
    'AlertWithLink': typeof import("../components/Alert/WithLink.vue")['default'],
    'BadgeCancel': typeof import("../components/Badge/Cancel.vue")['default'],
    'BadgeDefault': typeof import("../components/Badge/Default.vue")['default'],
    'BadgeIcon': typeof import("../components/Badge/Icon.vue")['default'],
    'BadgeLarge': typeof import("../components/Badge/Large.vue")['default'],
    'BadgeLink': typeof import("../components/Badge/Link.vue")['default'],
    'BadgeOutline': typeof import("../components/Badge/Outline.vue")['default'],
    'BadgePill': typeof import("../components/Badge/Pill.vue")['default'],
    'BadgePillOutline': typeof import("../components/Badge/PillOutline.vue")['default'],
    'BadgePositioned': typeof import("../components/Badge/Positioned.vue")['default'],
    'BadgeRectangle': typeof import("../components/Badge/Rectangle.vue")['default'],
    'BadgeSize': typeof import("../components/Badge/Size.vue")['default'],
    'BadgeStateColor': typeof import("../components/Badge/StateColor.vue")['default'],
    'BadgeText': typeof import("../components/Badge/Text.vue")['default'],
    'AvatarBadge': typeof import("../components/Avatar/Badge.vue")['default'],
    'AvatarCircle': typeof import("../components/Avatar/Circle.vue")['default'],
    'AvatarColor': typeof import("../components/Avatar/Color.vue")['default'],
    'AvatarDefault': typeof import("../components/Avatar/Default.vue")['default'],
    'AvatarDropDown': typeof import("../components/Avatar/DropDown.vue")['default'],
    'AvatarGroup1': typeof import("../components/Avatar/Group1.vue")['default'],
    'AvatarGroup2': typeof import("../components/Avatar/Group2.vue")['default'],
    'AvatarInfo': typeof import("../components/Avatar/Info.vue")['default'],
    'AvatarPresence': typeof import("../components/Avatar/Presence.vue")['default'],
    'AvatarPresenceRing': typeof import("../components/Avatar/PresenceRing.vue")['default'],
    'AvatarShadow': typeof import("../components/Avatar/Shadow.vue")['default'],
    'AvatarSize': typeof import("../components/Avatar/Size.vue")['default'],
    'AvatarSquare': typeof import("../components/Avatar/Square.vue")['default'],
    'BreadCrumbAlignment': typeof import("../components/BreadCrumb/Alignment.vue")['default'],
    'BreadCrumbArrow': typeof import("../components/BreadCrumb/Arrow.vue")['default'],
    'BreadCrumbDefault': typeof import("../components/BreadCrumb/Default.vue")['default'],
    'BreadCrumbIcon': typeof import("../components/BreadCrumb/Icon.vue")['default'],
    'BreadCrumbOutline': typeof import("../components/BreadCrumb/Outline.vue")['default'],
    'BreadCrumbSeparator': typeof import("../components/BreadCrumb/Separator.vue")['default'],
    'BreadCrumbSolid': typeof import("../components/BreadCrumb/Solid.vue")['default'],
    'CodeHighlight': typeof import("../components/CodeSnippet/CodeHighlight.vue")['default'],
    'ButtonAppsmith': typeof import("../components/Button/Appsmith.vue")['default'],
    'ButtonBlockButtons': typeof import("../components/Button/BlockButtons.vue")['default'],
    'ButtonInfo': typeof import("../components/Button/ButtonInfo.vue")['default'],
    'ButtonColoredShadow': typeof import("../components/Button/ColoredShadow.vue")['default'],
    'ButtonDarkColor': typeof import("../components/Button/DarkColor.vue")['default'],
    'ButtonDefault': typeof import("../components/Button/Default.vue")['default'],
    'ButtonDualIcon': typeof import("../components/Button/DualIcon.vue")['default'],
    'ButtonGradient': typeof import("../components/Button/Gradient.vue")['default'],
    'ButtonLightColor': typeof import("../components/Button/LightColor.vue")['default'],
    'ButtonOutline': typeof import("../components/Button/Outline.vue")['default'],
    'ButtonSize': typeof import("../components/Button/Size.vue")['default'],
    'ButtonStateColor': typeof import("../components/Button/StateColor.vue")['default'],
    'DropdownDefault': typeof import("../components/Dropdown/Default.vue")['default'],
    'DropdownDropDownInfo': typeof import("../components/Dropdown/DropDownInfo.vue")['default'],
    'DropdownNoIcon': typeof import("../components/Dropdown/NoIcon.vue")['default'],
    'DropdownOnlyHeading': typeof import("../components/Dropdown/OnlyHeading.vue")['default'],
    'DropdownProfile': typeof import("../components/Dropdown/Profile.vue")['default'],
    'DropdownWithIcon': typeof import("../components/Dropdown/WithIcon.vue")['default'],
    'FooterAppsmith': typeof import("../components/Footer/Appsmith.vue")['default'],
    'FooterDefault': typeof import("../components/Footer/Default.vue")['default'],
    'FooterInfo': typeof import("../components/Footer/FooterInfo.vue")['default'],
    'FooterLogoSection': typeof import("../components/Footer/LogoSection.vue")['default'],
    'FooterTwoRow': typeof import("../components/Footer/TwoRow.vue")['default'],
    'FormDefault': typeof import("../components/Form/Default.vue")['default'],
    'FormElement': typeof import("../components/Form/Element.vue")['default'],
    'FormFloatinglabel': typeof import("../components/Form/Floatinglabel.vue")['default'],
    'FormInfo': typeof import("../components/Form/FormInfo.vue")['default'],
    'HeadersHeading': typeof import("../components/Headers/Heading.vue")['default'],
    'HeadersSubHeading': typeof import("../components/Headers/SubHeading.vue")['default'],
    'NavigationMenuItems': typeof import("../components/Navigation/MenuItems.js")['default'],
    'PaginationDefault': typeof import("../components/Pagination/Default.vue")['default'],
    'PaginationInfo': typeof import("../components/Pagination/PaginationInfo.vue")['default'],
    'PaginationWithArrow': typeof import("../components/Pagination/WithArrow.vue")['default'],
    'RatingDefault': typeof import("../components/Rating/Default.vue")['default'],
    'RatingHeart': typeof import("../components/Rating/Heart.vue")['default'],
    'RatingImdb': typeof import("../components/Rating/Imdb.vue")['default'],
    'RatingOurCard': typeof import("../components/Rating/OurCard.vue")['default'],
    'RatingSmiley': typeof import("../components/Rating/Smiley.vue")['default'],
    'RatingYesOrNo': typeof import("../components/Rating/YesOrNo.vue")['default'],
    'SidebarDefault': typeof import("../components/Sidebar/Default.vue")['default'],
    'SidebarSectioned': typeof import("../components/Sidebar/Sectioned.vue")['default'],
    'SidebarSeparator': typeof import("../components/Sidebar/Separator.vue")['default'],
    'SidebarInfo': typeof import("../components/Sidebar/SidebarInfo.vue")['default'],
    'SidebarWithBadge': typeof import("../components/Sidebar/WithBadge.vue")['default'],
    'ToastDefault': typeof import("../components/Toast/Default.vue")['default'],
    'ToastOutline': typeof import("../components/Toast/Outline.vue")['default'],
    'ToastSolidColor': typeof import("../components/Toast/SolidColor.vue")['default'],
    'ToastStateColor': typeof import("../components/Toast/StateColor.vue")['default'],
    'ToastInfo': typeof import("../components/Toast/ToastInfo.vue")['default'],
    'ToastWithButton': typeof import("../components/Toast/WithButton.vue")['default'],
    'UtilsComponentPad': typeof import("../components/Utils/ComponentPad.vue")['default'],
    'UtilsCopyButton': typeof import("../components/Utils/CopyButton.vue")['default'],
    'UtilsHideCodeButton': typeof import("../components/Utils/HideCodeButton.vue")['default'],
    'UtilsShowCodeButton': typeof import("../components/Utils/ShowCodeButton.vue")['default'],
    'UtilsToast': typeof import("../components/Utils/Toast.vue")['default'],
    'AlertSnippetsBorderLeft': typeof import("../components/Alert/Snippets/BorderLeft.vue")['default'],
    'AlertSnippetsDefaultAlert': typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default'],
    'AlertSnippetsStateAlert': typeof import("../components/Alert/Snippets/StateAlert.vue")['default'],
    'AlertSnippetsWithBorder': typeof import("../components/Alert/Snippets/WithBorder.vue")['default'],
    'AlertSnippetsWithButton': typeof import("../components/Alert/Snippets/WithButton.vue")['default'],
    'AlertSnippetsWithIcon': typeof import("../components/Alert/Snippets/WithIcon.vue")['default'],
    'AlertSnippetsWithLink': typeof import("../components/Alert/Snippets/WithLink.vue")['default'],
    'BadgeSnippetsCancel': typeof import("../components/Badge/Snippets/Cancel.vue")['default'],
    'BadgeSnippetsDefault': typeof import("../components/Badge/Snippets/default.vue")['default'],
    'BadgeSnippetsIcon': typeof import("../components/Badge/Snippets/Icon.vue")['default'],
    'BadgeSnippetsLarge': typeof import("../components/Badge/Snippets/Large.vue")['default'],
    'BadgeSnippetsLink': typeof import("../components/Badge/Snippets/Link.vue")['default'],
    'BadgeSnippetsOutline': typeof import("../components/Badge/Snippets/Outline.vue")['default'],
    'BadgeSnippetsPill': typeof import("../components/Badge/Snippets/Pill.vue")['default'],
    'BadgeSnippetsPillOutline': typeof import("../components/Badge/Snippets/PillOutline.vue")['default'],
    'BadgeSnippetsPositioned': typeof import("../components/Badge/Snippets/Positioned.vue")['default'],
    'BadgeSnippetsRectangle': typeof import("../components/Badge/Snippets/Rectangle.vue")['default'],
    'BadgeSnippetsSize': typeof import("../components/Badge/Snippets/Size.vue")['default'],
    'BadgeSnippetsStateColor': typeof import("../components/Badge/Snippets/StateColor.vue")['default'],
    'BadgeSnippetsText': typeof import("../components/Badge/Snippets/Text.vue")['default'],
    'AvatarSnippetsBadge': typeof import("../components/Avatar/Snippets/Badge.vue")['default'],
    'AvatarSnippetsCircle': typeof import("../components/Avatar/Snippets/Circle.vue")['default'],
    'AvatarSnippetsColor': typeof import("../components/Avatar/Snippets/Color.vue")['default'],
    'AvatarSnippetsDefault': typeof import("../components/Avatar/Snippets/Default.vue")['default'],
    'AvatarSnippetsDropDown': typeof import("../components/Avatar/Snippets/DropDown.vue")['default'],
    'AvatarSnippetsGroup1': typeof import("../components/Avatar/Snippets/Group1.vue")['default'],
    'AvatarSnippetsGroup2': typeof import("../components/Avatar/Snippets/Group2.vue")['default'],
    'AvatarSnippetsInfo': typeof import("../components/Avatar/Snippets/Info.vue")['default'],
    'AvatarSnippetsPresence': typeof import("../components/Avatar/Snippets/Presence.vue")['default'],
    'AvatarSnippetsPresenceRing': typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default'],
    'AvatarSnippetsShadow': typeof import("../components/Avatar/Snippets/Shadow.vue")['default'],
    'AvatarSnippetsSize': typeof import("../components/Avatar/Snippets/Size.vue")['default'],
    'AvatarSnippetsSquare': typeof import("../components/Avatar/Snippets/Square.vue")['default'],
    'BreadCrumbSnippetsAlignment': typeof import("../components/BreadCrumb/Snippets/Alignment.vue")['default'],
    'BreadCrumbSnippetsArrow': typeof import("../components/BreadCrumb/Snippets/Arrow.vue")['default'],
    'BreadCrumbSnippetsDefault': typeof import("../components/BreadCrumb/Snippets/Default.vue")['default'],
    'BreadCrumbSnippetsIcon': typeof import("../components/BreadCrumb/Snippets/Icon.vue")['default'],
    'BreadCrumbSnippetsOutline': typeof import("../components/BreadCrumb/Snippets/Outline.vue")['default'],
    'BreadCrumbSnippetsSeparator': typeof import("../components/BreadCrumb/Snippets/Separator.vue")['default'],
    'BreadCrumbSnippetsSolid': typeof import("../components/BreadCrumb/Snippets/Solid.vue")['default'],
    'ButtonSnippetsAppsmith': typeof import("../components/Button/Snippets/Appsmith.vue")['default'],
    'ButtonSnippetsBlockButtons': typeof import("../components/Button/Snippets/BlockButtons.vue")['default'],
    'ButtonSnippetsColoredShadow': typeof import("../components/Button/Snippets/ColoredShadow.vue")['default'],
    'ButtonSnippetsDarkColor': typeof import("../components/Button/Snippets/DarkColor.vue")['default'],
    'ButtonSnippetsDefault': typeof import("../components/Button/Snippets/Default.vue")['default'],
    'ButtonSnippetsDualIcon': typeof import("../components/Button/Snippets/DualIcon.vue")['default'],
    'ButtonSnippetsGradient': typeof import("../components/Button/Snippets/Gradient.vue")['default'],
    'ButtonSnippetsLightColor': typeof import("../components/Button/Snippets/LightColor.vue")['default'],
    'ButtonSnippetsOutline': typeof import("../components/Button/Snippets/Outline.vue")['default'],
    'ButtonSnippetsSize': typeof import("../components/Button/Snippets/Size.vue")['default'],
    'ButtonSnippetsStateColor': typeof import("../components/Button/Snippets/StateColor.vue")['default'],
    'DropdownSnippetsDefault': typeof import("../components/Dropdown/Snippets/Default.vue")['default'],
    'DropdownSnippetsNoIcon': typeof import("../components/Dropdown/Snippets/NoIcon.vue")['default'],
    'DropdownSnippetsOnlyHeading': typeof import("../components/Dropdown/Snippets/OnlyHeading.vue")['default'],
    'DropdownSnippetsProfile': typeof import("../components/Dropdown/Snippets/Profile.vue")['default'],
    'DropdownSnippetsWithIcon': typeof import("../components/Dropdown/Snippets/WithIcon.vue")['default'],
    'FooterSnippetsAppsmith': typeof import("../components/Footer/Snippets/Appsmith.vue")['default'],
    'FooterSnippetsDefault': typeof import("../components/Footer/Snippets/Default.vue")['default'],
    'FooterSnippetsLogoSection': typeof import("../components/Footer/Snippets/LogoSection.vue")['default'],
    'FooterSnippetsTwoRow': typeof import("../components/Footer/Snippets/TwoRow.vue")['default'],
    'FormSnippetsDefault': typeof import("../components/Form/Snippets/Default.vue")['default'],
    'FormSnippetsElement': typeof import("../components/Form/Snippets/Element.vue")['default'],
    'FormSnippetsFloatinglabel': typeof import("../components/Form/Snippets/Floatinglabel.vue")['default'],
    'PaginationSnippetsDefault': typeof import("../components/Pagination/Snippets/Default.vue")['default'],
    'PaginationSnippetsWithArrow': typeof import("../components/Pagination/Snippets/WithArrow.vue")['default'],
    'RatingSnippetsDefault': typeof import("../components/Rating/Snippets/Default.vue")['default'],
    'RatingSnippetsHeart': typeof import("../components/Rating/Snippets/Heart.vue")['default'],
    'RatingSnippetsImdb': typeof import("../components/Rating/Snippets/Imdb.vue")['default'],
    'RatingSnippetsOurCard': typeof import("../components/Rating/Snippets/OurCard.vue")['default'],
    'RatingSnippetsSmiley': typeof import("../components/Rating/Snippets/Smiley.vue")['default'],
    'RatingSnippetsYesOrNo': typeof import("../components/Rating/Snippets/YesOrNo.vue")['default'],
    'SidebarSnippetsDefault': typeof import("../components/Sidebar/Snippets/Default.vue")['default'],
    'SidebarSnippetsSectioned': typeof import("../components/Sidebar/Snippets/Sectioned.vue")['default'],
    'SidebarSnippetsSeparator': typeof import("../components/Sidebar/Snippets/Separator.vue")['default'],
    'SidebarSnippetsWithBadge': typeof import("../components/Sidebar/Snippets/WithBadge.vue")['default'],
    'ToastSnippetsDefault': typeof import("../components/Toast/Snippets/Default.vue")['default'],
    'ToastSnippetsOutline': typeof import("../components/Toast/Snippets/Outline.vue")['default'],
    'ToastSnippetsSolidColor': typeof import("../components/Toast/Snippets/SolidColor.vue")['default'],
    'ToastSnippetsStateColor': typeof import("../components/Toast/Snippets/StateColor.vue")['default'],
    'ToastSnippetsWithButton': typeof import("../components/Toast/Snippets/WithButton.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyAlertInfo': typeof import("../components/Alert/AlertInfo.vue")['default'],
    'LazyAlertBorderLeft': typeof import("../components/Alert/BorderLeft.vue")['default'],
    'LazyAlertDefaultAlert': typeof import("../components/Alert/DefaultAlert.vue")['default'],
    'LazyAlertStateAlert': typeof import("../components/Alert/StateAlert.vue")['default'],
    'LazyAlertWithBorder': typeof import("../components/Alert/WithBorder.vue")['default'],
    'LazyAlertWithButton': typeof import("../components/Alert/WithButton.vue")['default'],
    'LazyAlertWithIcon': typeof import("../components/Alert/WithIcon.vue")['default'],
    'LazyAlertWithLink': typeof import("../components/Alert/WithLink.vue")['default'],
    'LazyBadgeCancel': typeof import("../components/Badge/Cancel.vue")['default'],
    'LazyBadgeDefault': typeof import("../components/Badge/Default.vue")['default'],
    'LazyBadgeIcon': typeof import("../components/Badge/Icon.vue")['default'],
    'LazyBadgeLarge': typeof import("../components/Badge/Large.vue")['default'],
    'LazyBadgeLink': typeof import("../components/Badge/Link.vue")['default'],
    'LazyBadgeOutline': typeof import("../components/Badge/Outline.vue")['default'],
    'LazyBadgePill': typeof import("../components/Badge/Pill.vue")['default'],
    'LazyBadgePillOutline': typeof import("../components/Badge/PillOutline.vue")['default'],
    'LazyBadgePositioned': typeof import("../components/Badge/Positioned.vue")['default'],
    'LazyBadgeRectangle': typeof import("../components/Badge/Rectangle.vue")['default'],
    'LazyBadgeSize': typeof import("../components/Badge/Size.vue")['default'],
    'LazyBadgeStateColor': typeof import("../components/Badge/StateColor.vue")['default'],
    'LazyBadgeText': typeof import("../components/Badge/Text.vue")['default'],
    'LazyAvatarBadge': typeof import("../components/Avatar/Badge.vue")['default'],
    'LazyAvatarCircle': typeof import("../components/Avatar/Circle.vue")['default'],
    'LazyAvatarColor': typeof import("../components/Avatar/Color.vue")['default'],
    'LazyAvatarDefault': typeof import("../components/Avatar/Default.vue")['default'],
    'LazyAvatarDropDown': typeof import("../components/Avatar/DropDown.vue")['default'],
    'LazyAvatarGroup1': typeof import("../components/Avatar/Group1.vue")['default'],
    'LazyAvatarGroup2': typeof import("../components/Avatar/Group2.vue")['default'],
    'LazyAvatarInfo': typeof import("../components/Avatar/Info.vue")['default'],
    'LazyAvatarPresence': typeof import("../components/Avatar/Presence.vue")['default'],
    'LazyAvatarPresenceRing': typeof import("../components/Avatar/PresenceRing.vue")['default'],
    'LazyAvatarShadow': typeof import("../components/Avatar/Shadow.vue")['default'],
    'LazyAvatarSize': typeof import("../components/Avatar/Size.vue")['default'],
    'LazyAvatarSquare': typeof import("../components/Avatar/Square.vue")['default'],
    'LazyBreadCrumbAlignment': typeof import("../components/BreadCrumb/Alignment.vue")['default'],
    'LazyBreadCrumbArrow': typeof import("../components/BreadCrumb/Arrow.vue")['default'],
    'LazyBreadCrumbDefault': typeof import("../components/BreadCrumb/Default.vue")['default'],
    'LazyBreadCrumbIcon': typeof import("../components/BreadCrumb/Icon.vue")['default'],
    'LazyBreadCrumbOutline': typeof import("../components/BreadCrumb/Outline.vue")['default'],
    'LazyBreadCrumbSeparator': typeof import("../components/BreadCrumb/Separator.vue")['default'],
    'LazyBreadCrumbSolid': typeof import("../components/BreadCrumb/Solid.vue")['default'],
    'LazyCodeHighlight': typeof import("../components/CodeSnippet/CodeHighlight.vue")['default'],
    'LazyButtonAppsmith': typeof import("../components/Button/Appsmith.vue")['default'],
    'LazyButtonBlockButtons': typeof import("../components/Button/BlockButtons.vue")['default'],
    'LazyButtonInfo': typeof import("../components/Button/ButtonInfo.vue")['default'],
    'LazyButtonColoredShadow': typeof import("../components/Button/ColoredShadow.vue")['default'],
    'LazyButtonDarkColor': typeof import("../components/Button/DarkColor.vue")['default'],
    'LazyButtonDefault': typeof import("../components/Button/Default.vue")['default'],
    'LazyButtonDualIcon': typeof import("../components/Button/DualIcon.vue")['default'],
    'LazyButtonGradient': typeof import("../components/Button/Gradient.vue")['default'],
    'LazyButtonLightColor': typeof import("../components/Button/LightColor.vue")['default'],
    'LazyButtonOutline': typeof import("../components/Button/Outline.vue")['default'],
    'LazyButtonSize': typeof import("../components/Button/Size.vue")['default'],
    'LazyButtonStateColor': typeof import("../components/Button/StateColor.vue")['default'],
    'LazyDropdownDefault': typeof import("../components/Dropdown/Default.vue")['default'],
    'LazyDropdownDropDownInfo': typeof import("../components/Dropdown/DropDownInfo.vue")['default'],
    'LazyDropdownNoIcon': typeof import("../components/Dropdown/NoIcon.vue")['default'],
    'LazyDropdownOnlyHeading': typeof import("../components/Dropdown/OnlyHeading.vue")['default'],
    'LazyDropdownProfile': typeof import("../components/Dropdown/Profile.vue")['default'],
    'LazyDropdownWithIcon': typeof import("../components/Dropdown/WithIcon.vue")['default'],
    'LazyFooterAppsmith': typeof import("../components/Footer/Appsmith.vue")['default'],
    'LazyFooterDefault': typeof import("../components/Footer/Default.vue")['default'],
    'LazyFooterInfo': typeof import("../components/Footer/FooterInfo.vue")['default'],
    'LazyFooterLogoSection': typeof import("../components/Footer/LogoSection.vue")['default'],
    'LazyFooterTwoRow': typeof import("../components/Footer/TwoRow.vue")['default'],
    'LazyFormDefault': typeof import("../components/Form/Default.vue")['default'],
    'LazyFormElement': typeof import("../components/Form/Element.vue")['default'],
    'LazyFormFloatinglabel': typeof import("../components/Form/Floatinglabel.vue")['default'],
    'LazyFormInfo': typeof import("../components/Form/FormInfo.vue")['default'],
    'LazyHeadersHeading': typeof import("../components/Headers/Heading.vue")['default'],
    'LazyHeadersSubHeading': typeof import("../components/Headers/SubHeading.vue")['default'],
    'LazyNavigationMenuItems': typeof import("../components/Navigation/MenuItems.js")['default'],
    'LazyPaginationDefault': typeof import("../components/Pagination/Default.vue")['default'],
    'LazyPaginationInfo': typeof import("../components/Pagination/PaginationInfo.vue")['default'],
    'LazyPaginationWithArrow': typeof import("../components/Pagination/WithArrow.vue")['default'],
    'LazyRatingDefault': typeof import("../components/Rating/Default.vue")['default'],
    'LazyRatingHeart': typeof import("../components/Rating/Heart.vue")['default'],
    'LazyRatingImdb': typeof import("../components/Rating/Imdb.vue")['default'],
    'LazyRatingOurCard': typeof import("../components/Rating/OurCard.vue")['default'],
    'LazyRatingSmiley': typeof import("../components/Rating/Smiley.vue")['default'],
    'LazyRatingYesOrNo': typeof import("../components/Rating/YesOrNo.vue")['default'],
    'LazySidebarDefault': typeof import("../components/Sidebar/Default.vue")['default'],
    'LazySidebarSectioned': typeof import("../components/Sidebar/Sectioned.vue")['default'],
    'LazySidebarSeparator': typeof import("../components/Sidebar/Separator.vue")['default'],
    'LazySidebarInfo': typeof import("../components/Sidebar/SidebarInfo.vue")['default'],
    'LazySidebarWithBadge': typeof import("../components/Sidebar/WithBadge.vue")['default'],
    'LazyToastDefault': typeof import("../components/Toast/Default.vue")['default'],
    'LazyToastOutline': typeof import("../components/Toast/Outline.vue")['default'],
    'LazyToastSolidColor': typeof import("../components/Toast/SolidColor.vue")['default'],
    'LazyToastStateColor': typeof import("../components/Toast/StateColor.vue")['default'],
    'LazyToastInfo': typeof import("../components/Toast/ToastInfo.vue")['default'],
    'LazyToastWithButton': typeof import("../components/Toast/WithButton.vue")['default'],
    'LazyUtilsComponentPad': typeof import("../components/Utils/ComponentPad.vue")['default'],
    'LazyUtilsCopyButton': typeof import("../components/Utils/CopyButton.vue")['default'],
    'LazyUtilsHideCodeButton': typeof import("../components/Utils/HideCodeButton.vue")['default'],
    'LazyUtilsShowCodeButton': typeof import("../components/Utils/ShowCodeButton.vue")['default'],
    'LazyUtilsToast': typeof import("../components/Utils/Toast.vue")['default'],
    'LazyAlertSnippetsBorderLeft': typeof import("../components/Alert/Snippets/BorderLeft.vue")['default'],
    'LazyAlertSnippetsDefaultAlert': typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default'],
    'LazyAlertSnippetsStateAlert': typeof import("../components/Alert/Snippets/StateAlert.vue")['default'],
    'LazyAlertSnippetsWithBorder': typeof import("../components/Alert/Snippets/WithBorder.vue")['default'],
    'LazyAlertSnippetsWithButton': typeof import("../components/Alert/Snippets/WithButton.vue")['default'],
    'LazyAlertSnippetsWithIcon': typeof import("../components/Alert/Snippets/WithIcon.vue")['default'],
    'LazyAlertSnippetsWithLink': typeof import("../components/Alert/Snippets/WithLink.vue")['default'],
    'LazyBadgeSnippetsCancel': typeof import("../components/Badge/Snippets/Cancel.vue")['default'],
    'LazyBadgeSnippetsDefault': typeof import("../components/Badge/Snippets/default.vue")['default'],
    'LazyBadgeSnippetsIcon': typeof import("../components/Badge/Snippets/Icon.vue")['default'],
    'LazyBadgeSnippetsLarge': typeof import("../components/Badge/Snippets/Large.vue")['default'],
    'LazyBadgeSnippetsLink': typeof import("../components/Badge/Snippets/Link.vue")['default'],
    'LazyBadgeSnippetsOutline': typeof import("../components/Badge/Snippets/Outline.vue")['default'],
    'LazyBadgeSnippetsPill': typeof import("../components/Badge/Snippets/Pill.vue")['default'],
    'LazyBadgeSnippetsPillOutline': typeof import("../components/Badge/Snippets/PillOutline.vue")['default'],
    'LazyBadgeSnippetsPositioned': typeof import("../components/Badge/Snippets/Positioned.vue")['default'],
    'LazyBadgeSnippetsRectangle': typeof import("../components/Badge/Snippets/Rectangle.vue")['default'],
    'LazyBadgeSnippetsSize': typeof import("../components/Badge/Snippets/Size.vue")['default'],
    'LazyBadgeSnippetsStateColor': typeof import("../components/Badge/Snippets/StateColor.vue")['default'],
    'LazyBadgeSnippetsText': typeof import("../components/Badge/Snippets/Text.vue")['default'],
    'LazyAvatarSnippetsBadge': typeof import("../components/Avatar/Snippets/Badge.vue")['default'],
    'LazyAvatarSnippetsCircle': typeof import("../components/Avatar/Snippets/Circle.vue")['default'],
    'LazyAvatarSnippetsColor': typeof import("../components/Avatar/Snippets/Color.vue")['default'],
    'LazyAvatarSnippetsDefault': typeof import("../components/Avatar/Snippets/Default.vue")['default'],
    'LazyAvatarSnippetsDropDown': typeof import("../components/Avatar/Snippets/DropDown.vue")['default'],
    'LazyAvatarSnippetsGroup1': typeof import("../components/Avatar/Snippets/Group1.vue")['default'],
    'LazyAvatarSnippetsGroup2': typeof import("../components/Avatar/Snippets/Group2.vue")['default'],
    'LazyAvatarSnippetsInfo': typeof import("../components/Avatar/Snippets/Info.vue")['default'],
    'LazyAvatarSnippetsPresence': typeof import("../components/Avatar/Snippets/Presence.vue")['default'],
    'LazyAvatarSnippetsPresenceRing': typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default'],
    'LazyAvatarSnippetsShadow': typeof import("../components/Avatar/Snippets/Shadow.vue")['default'],
    'LazyAvatarSnippetsSize': typeof import("../components/Avatar/Snippets/Size.vue")['default'],
    'LazyAvatarSnippetsSquare': typeof import("../components/Avatar/Snippets/Square.vue")['default'],
    'LazyBreadCrumbSnippetsAlignment': typeof import("../components/BreadCrumb/Snippets/Alignment.vue")['default'],
    'LazyBreadCrumbSnippetsArrow': typeof import("../components/BreadCrumb/Snippets/Arrow.vue")['default'],
    'LazyBreadCrumbSnippetsDefault': typeof import("../components/BreadCrumb/Snippets/Default.vue")['default'],
    'LazyBreadCrumbSnippetsIcon': typeof import("../components/BreadCrumb/Snippets/Icon.vue")['default'],
    'LazyBreadCrumbSnippetsOutline': typeof import("../components/BreadCrumb/Snippets/Outline.vue")['default'],
    'LazyBreadCrumbSnippetsSeparator': typeof import("../components/BreadCrumb/Snippets/Separator.vue")['default'],
    'LazyBreadCrumbSnippetsSolid': typeof import("../components/BreadCrumb/Snippets/Solid.vue")['default'],
    'LazyButtonSnippetsAppsmith': typeof import("../components/Button/Snippets/Appsmith.vue")['default'],
    'LazyButtonSnippetsBlockButtons': typeof import("../components/Button/Snippets/BlockButtons.vue")['default'],
    'LazyButtonSnippetsColoredShadow': typeof import("../components/Button/Snippets/ColoredShadow.vue")['default'],
    'LazyButtonSnippetsDarkColor': typeof import("../components/Button/Snippets/DarkColor.vue")['default'],
    'LazyButtonSnippetsDefault': typeof import("../components/Button/Snippets/Default.vue")['default'],
    'LazyButtonSnippetsDualIcon': typeof import("../components/Button/Snippets/DualIcon.vue")['default'],
    'LazyButtonSnippetsGradient': typeof import("../components/Button/Snippets/Gradient.vue")['default'],
    'LazyButtonSnippetsLightColor': typeof import("../components/Button/Snippets/LightColor.vue")['default'],
    'LazyButtonSnippetsOutline': typeof import("../components/Button/Snippets/Outline.vue")['default'],
    'LazyButtonSnippetsSize': typeof import("../components/Button/Snippets/Size.vue")['default'],
    'LazyButtonSnippetsStateColor': typeof import("../components/Button/Snippets/StateColor.vue")['default'],
    'LazyDropdownSnippetsDefault': typeof import("../components/Dropdown/Snippets/Default.vue")['default'],
    'LazyDropdownSnippetsNoIcon': typeof import("../components/Dropdown/Snippets/NoIcon.vue")['default'],
    'LazyDropdownSnippetsOnlyHeading': typeof import("../components/Dropdown/Snippets/OnlyHeading.vue")['default'],
    'LazyDropdownSnippetsProfile': typeof import("../components/Dropdown/Snippets/Profile.vue")['default'],
    'LazyDropdownSnippetsWithIcon': typeof import("../components/Dropdown/Snippets/WithIcon.vue")['default'],
    'LazyFooterSnippetsAppsmith': typeof import("../components/Footer/Snippets/Appsmith.vue")['default'],
    'LazyFooterSnippetsDefault': typeof import("../components/Footer/Snippets/Default.vue")['default'],
    'LazyFooterSnippetsLogoSection': typeof import("../components/Footer/Snippets/LogoSection.vue")['default'],
    'LazyFooterSnippetsTwoRow': typeof import("../components/Footer/Snippets/TwoRow.vue")['default'],
    'LazyFormSnippetsDefault': typeof import("../components/Form/Snippets/Default.vue")['default'],
    'LazyFormSnippetsElement': typeof import("../components/Form/Snippets/Element.vue")['default'],
    'LazyFormSnippetsFloatinglabel': typeof import("../components/Form/Snippets/Floatinglabel.vue")['default'],
    'LazyPaginationSnippetsDefault': typeof import("../components/Pagination/Snippets/Default.vue")['default'],
    'LazyPaginationSnippetsWithArrow': typeof import("../components/Pagination/Snippets/WithArrow.vue")['default'],
    'LazyRatingSnippetsDefault': typeof import("../components/Rating/Snippets/Default.vue")['default'],
    'LazyRatingSnippetsHeart': typeof import("../components/Rating/Snippets/Heart.vue")['default'],
    'LazyRatingSnippetsImdb': typeof import("../components/Rating/Snippets/Imdb.vue")['default'],
    'LazyRatingSnippetsOurCard': typeof import("../components/Rating/Snippets/OurCard.vue")['default'],
    'LazyRatingSnippetsSmiley': typeof import("../components/Rating/Snippets/Smiley.vue")['default'],
    'LazyRatingSnippetsYesOrNo': typeof import("../components/Rating/Snippets/YesOrNo.vue")['default'],
    'LazySidebarSnippetsDefault': typeof import("../components/Sidebar/Snippets/Default.vue")['default'],
    'LazySidebarSnippetsSectioned': typeof import("../components/Sidebar/Snippets/Sectioned.vue")['default'],
    'LazySidebarSnippetsSeparator': typeof import("../components/Sidebar/Snippets/Separator.vue")['default'],
    'LazySidebarSnippetsWithBadge': typeof import("../components/Sidebar/Snippets/WithBadge.vue")['default'],
    'LazyToastSnippetsDefault': typeof import("../components/Toast/Snippets/Default.vue")['default'],
    'LazyToastSnippetsOutline': typeof import("../components/Toast/Snippets/Outline.vue")['default'],
    'LazyToastSnippetsSolidColor': typeof import("../components/Toast/Snippets/SolidColor.vue")['default'],
    'LazyToastSnippetsStateColor': typeof import("../components/Toast/Snippets/StateColor.vue")['default'],
    'LazyToastSnippetsWithButton': typeof import("../components/Toast/Snippets/WithButton.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const AlertInfo: typeof import("../components/Alert/AlertInfo.vue")['default']
export const AlertBorderLeft: typeof import("../components/Alert/BorderLeft.vue")['default']
export const AlertDefaultAlert: typeof import("../components/Alert/DefaultAlert.vue")['default']
export const AlertStateAlert: typeof import("../components/Alert/StateAlert.vue")['default']
export const AlertWithBorder: typeof import("../components/Alert/WithBorder.vue")['default']
export const AlertWithButton: typeof import("../components/Alert/WithButton.vue")['default']
export const AlertWithIcon: typeof import("../components/Alert/WithIcon.vue")['default']
export const AlertWithLink: typeof import("../components/Alert/WithLink.vue")['default']
export const BadgeCancel: typeof import("../components/Badge/Cancel.vue")['default']
export const BadgeDefault: typeof import("../components/Badge/Default.vue")['default']
export const BadgeIcon: typeof import("../components/Badge/Icon.vue")['default']
export const BadgeLarge: typeof import("../components/Badge/Large.vue")['default']
export const BadgeLink: typeof import("../components/Badge/Link.vue")['default']
export const BadgeOutline: typeof import("../components/Badge/Outline.vue")['default']
export const BadgePill: typeof import("../components/Badge/Pill.vue")['default']
export const BadgePillOutline: typeof import("../components/Badge/PillOutline.vue")['default']
export const BadgePositioned: typeof import("../components/Badge/Positioned.vue")['default']
export const BadgeRectangle: typeof import("../components/Badge/Rectangle.vue")['default']
export const BadgeSize: typeof import("../components/Badge/Size.vue")['default']
export const BadgeStateColor: typeof import("../components/Badge/StateColor.vue")['default']
export const BadgeText: typeof import("../components/Badge/Text.vue")['default']
export const AvatarBadge: typeof import("../components/Avatar/Badge.vue")['default']
export const AvatarCircle: typeof import("../components/Avatar/Circle.vue")['default']
export const AvatarColor: typeof import("../components/Avatar/Color.vue")['default']
export const AvatarDefault: typeof import("../components/Avatar/Default.vue")['default']
export const AvatarDropDown: typeof import("../components/Avatar/DropDown.vue")['default']
export const AvatarGroup1: typeof import("../components/Avatar/Group1.vue")['default']
export const AvatarGroup2: typeof import("../components/Avatar/Group2.vue")['default']
export const AvatarInfo: typeof import("../components/Avatar/Info.vue")['default']
export const AvatarPresence: typeof import("../components/Avatar/Presence.vue")['default']
export const AvatarPresenceRing: typeof import("../components/Avatar/PresenceRing.vue")['default']
export const AvatarShadow: typeof import("../components/Avatar/Shadow.vue")['default']
export const AvatarSize: typeof import("../components/Avatar/Size.vue")['default']
export const AvatarSquare: typeof import("../components/Avatar/Square.vue")['default']
export const BreadCrumbAlignment: typeof import("../components/BreadCrumb/Alignment.vue")['default']
export const BreadCrumbArrow: typeof import("../components/BreadCrumb/Arrow.vue")['default']
export const BreadCrumbDefault: typeof import("../components/BreadCrumb/Default.vue")['default']
export const BreadCrumbIcon: typeof import("../components/BreadCrumb/Icon.vue")['default']
export const BreadCrumbOutline: typeof import("../components/BreadCrumb/Outline.vue")['default']
export const BreadCrumbSeparator: typeof import("../components/BreadCrumb/Separator.vue")['default']
export const BreadCrumbSolid: typeof import("../components/BreadCrumb/Solid.vue")['default']
export const CodeHighlight: typeof import("../components/CodeSnippet/CodeHighlight.vue")['default']
export const ButtonAppsmith: typeof import("../components/Button/Appsmith.vue")['default']
export const ButtonBlockButtons: typeof import("../components/Button/BlockButtons.vue")['default']
export const ButtonInfo: typeof import("../components/Button/ButtonInfo.vue")['default']
export const ButtonColoredShadow: typeof import("../components/Button/ColoredShadow.vue")['default']
export const ButtonDarkColor: typeof import("../components/Button/DarkColor.vue")['default']
export const ButtonDefault: typeof import("../components/Button/Default.vue")['default']
export const ButtonDualIcon: typeof import("../components/Button/DualIcon.vue")['default']
export const ButtonGradient: typeof import("../components/Button/Gradient.vue")['default']
export const ButtonLightColor: typeof import("../components/Button/LightColor.vue")['default']
export const ButtonOutline: typeof import("../components/Button/Outline.vue")['default']
export const ButtonSize: typeof import("../components/Button/Size.vue")['default']
export const ButtonStateColor: typeof import("../components/Button/StateColor.vue")['default']
export const DropdownDefault: typeof import("../components/Dropdown/Default.vue")['default']
export const DropdownDropDownInfo: typeof import("../components/Dropdown/DropDownInfo.vue")['default']
export const DropdownNoIcon: typeof import("../components/Dropdown/NoIcon.vue")['default']
export const DropdownOnlyHeading: typeof import("../components/Dropdown/OnlyHeading.vue")['default']
export const DropdownProfile: typeof import("../components/Dropdown/Profile.vue")['default']
export const DropdownWithIcon: typeof import("../components/Dropdown/WithIcon.vue")['default']
export const FooterAppsmith: typeof import("../components/Footer/Appsmith.vue")['default']
export const FooterDefault: typeof import("../components/Footer/Default.vue")['default']
export const FooterInfo: typeof import("../components/Footer/FooterInfo.vue")['default']
export const FooterLogoSection: typeof import("../components/Footer/LogoSection.vue")['default']
export const FooterTwoRow: typeof import("../components/Footer/TwoRow.vue")['default']
export const FormDefault: typeof import("../components/Form/Default.vue")['default']
export const FormElement: typeof import("../components/Form/Element.vue")['default']
export const FormFloatinglabel: typeof import("../components/Form/Floatinglabel.vue")['default']
export const FormInfo: typeof import("../components/Form/FormInfo.vue")['default']
export const HeadersHeading: typeof import("../components/Headers/Heading.vue")['default']
export const HeadersSubHeading: typeof import("../components/Headers/SubHeading.vue")['default']
export const NavigationMenuItems: typeof import("../components/Navigation/MenuItems.js")['default']
export const PaginationDefault: typeof import("../components/Pagination/Default.vue")['default']
export const PaginationInfo: typeof import("../components/Pagination/PaginationInfo.vue")['default']
export const PaginationWithArrow: typeof import("../components/Pagination/WithArrow.vue")['default']
export const RatingDefault: typeof import("../components/Rating/Default.vue")['default']
export const RatingHeart: typeof import("../components/Rating/Heart.vue")['default']
export const RatingImdb: typeof import("../components/Rating/Imdb.vue")['default']
export const RatingOurCard: typeof import("../components/Rating/OurCard.vue")['default']
export const RatingSmiley: typeof import("../components/Rating/Smiley.vue")['default']
export const RatingYesOrNo: typeof import("../components/Rating/YesOrNo.vue")['default']
export const SidebarDefault: typeof import("../components/Sidebar/Default.vue")['default']
export const SidebarSectioned: typeof import("../components/Sidebar/Sectioned.vue")['default']
export const SidebarSeparator: typeof import("../components/Sidebar/Separator.vue")['default']
export const SidebarInfo: typeof import("../components/Sidebar/SidebarInfo.vue")['default']
export const SidebarWithBadge: typeof import("../components/Sidebar/WithBadge.vue")['default']
export const ToastDefault: typeof import("../components/Toast/Default.vue")['default']
export const ToastOutline: typeof import("../components/Toast/Outline.vue")['default']
export const ToastSolidColor: typeof import("../components/Toast/SolidColor.vue")['default']
export const ToastStateColor: typeof import("../components/Toast/StateColor.vue")['default']
export const ToastInfo: typeof import("../components/Toast/ToastInfo.vue")['default']
export const ToastWithButton: typeof import("../components/Toast/WithButton.vue")['default']
export const UtilsComponentPad: typeof import("../components/Utils/ComponentPad.vue")['default']
export const UtilsCopyButton: typeof import("../components/Utils/CopyButton.vue")['default']
export const UtilsHideCodeButton: typeof import("../components/Utils/HideCodeButton.vue")['default']
export const UtilsShowCodeButton: typeof import("../components/Utils/ShowCodeButton.vue")['default']
export const UtilsToast: typeof import("../components/Utils/Toast.vue")['default']
export const AlertSnippetsBorderLeft: typeof import("../components/Alert/Snippets/BorderLeft.vue")['default']
export const AlertSnippetsDefaultAlert: typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default']
export const AlertSnippetsStateAlert: typeof import("../components/Alert/Snippets/StateAlert.vue")['default']
export const AlertSnippetsWithBorder: typeof import("../components/Alert/Snippets/WithBorder.vue")['default']
export const AlertSnippetsWithButton: typeof import("../components/Alert/Snippets/WithButton.vue")['default']
export const AlertSnippetsWithIcon: typeof import("../components/Alert/Snippets/WithIcon.vue")['default']
export const AlertSnippetsWithLink: typeof import("../components/Alert/Snippets/WithLink.vue")['default']
export const BadgeSnippetsCancel: typeof import("../components/Badge/Snippets/Cancel.vue")['default']
export const BadgeSnippetsDefault: typeof import("../components/Badge/Snippets/default.vue")['default']
export const BadgeSnippetsIcon: typeof import("../components/Badge/Snippets/Icon.vue")['default']
export const BadgeSnippetsLarge: typeof import("../components/Badge/Snippets/Large.vue")['default']
export const BadgeSnippetsLink: typeof import("../components/Badge/Snippets/Link.vue")['default']
export const BadgeSnippetsOutline: typeof import("../components/Badge/Snippets/Outline.vue")['default']
export const BadgeSnippetsPill: typeof import("../components/Badge/Snippets/Pill.vue")['default']
export const BadgeSnippetsPillOutline: typeof import("../components/Badge/Snippets/PillOutline.vue")['default']
export const BadgeSnippetsPositioned: typeof import("../components/Badge/Snippets/Positioned.vue")['default']
export const BadgeSnippetsRectangle: typeof import("../components/Badge/Snippets/Rectangle.vue")['default']
export const BadgeSnippetsSize: typeof import("../components/Badge/Snippets/Size.vue")['default']
export const BadgeSnippetsStateColor: typeof import("../components/Badge/Snippets/StateColor.vue")['default']
export const BadgeSnippetsText: typeof import("../components/Badge/Snippets/Text.vue")['default']
export const AvatarSnippetsBadge: typeof import("../components/Avatar/Snippets/Badge.vue")['default']
export const AvatarSnippetsCircle: typeof import("../components/Avatar/Snippets/Circle.vue")['default']
export const AvatarSnippetsColor: typeof import("../components/Avatar/Snippets/Color.vue")['default']
export const AvatarSnippetsDefault: typeof import("../components/Avatar/Snippets/Default.vue")['default']
export const AvatarSnippetsDropDown: typeof import("../components/Avatar/Snippets/DropDown.vue")['default']
export const AvatarSnippetsGroup1: typeof import("../components/Avatar/Snippets/Group1.vue")['default']
export const AvatarSnippetsGroup2: typeof import("../components/Avatar/Snippets/Group2.vue")['default']
export const AvatarSnippetsInfo: typeof import("../components/Avatar/Snippets/Info.vue")['default']
export const AvatarSnippetsPresence: typeof import("../components/Avatar/Snippets/Presence.vue")['default']
export const AvatarSnippetsPresenceRing: typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default']
export const AvatarSnippetsShadow: typeof import("../components/Avatar/Snippets/Shadow.vue")['default']
export const AvatarSnippetsSize: typeof import("../components/Avatar/Snippets/Size.vue")['default']
export const AvatarSnippetsSquare: typeof import("../components/Avatar/Snippets/Square.vue")['default']
export const BreadCrumbSnippetsAlignment: typeof import("../components/BreadCrumb/Snippets/Alignment.vue")['default']
export const BreadCrumbSnippetsArrow: typeof import("../components/BreadCrumb/Snippets/Arrow.vue")['default']
export const BreadCrumbSnippetsDefault: typeof import("../components/BreadCrumb/Snippets/Default.vue")['default']
export const BreadCrumbSnippetsIcon: typeof import("../components/BreadCrumb/Snippets/Icon.vue")['default']
export const BreadCrumbSnippetsOutline: typeof import("../components/BreadCrumb/Snippets/Outline.vue")['default']
export const BreadCrumbSnippetsSeparator: typeof import("../components/BreadCrumb/Snippets/Separator.vue")['default']
export const BreadCrumbSnippetsSolid: typeof import("../components/BreadCrumb/Snippets/Solid.vue")['default']
export const ButtonSnippetsAppsmith: typeof import("../components/Button/Snippets/Appsmith.vue")['default']
export const ButtonSnippetsBlockButtons: typeof import("../components/Button/Snippets/BlockButtons.vue")['default']
export const ButtonSnippetsColoredShadow: typeof import("../components/Button/Snippets/ColoredShadow.vue")['default']
export const ButtonSnippetsDarkColor: typeof import("../components/Button/Snippets/DarkColor.vue")['default']
export const ButtonSnippetsDefault: typeof import("../components/Button/Snippets/Default.vue")['default']
export const ButtonSnippetsDualIcon: typeof import("../components/Button/Snippets/DualIcon.vue")['default']
export const ButtonSnippetsGradient: typeof import("../components/Button/Snippets/Gradient.vue")['default']
export const ButtonSnippetsLightColor: typeof import("../components/Button/Snippets/LightColor.vue")['default']
export const ButtonSnippetsOutline: typeof import("../components/Button/Snippets/Outline.vue")['default']
export const ButtonSnippetsSize: typeof import("../components/Button/Snippets/Size.vue")['default']
export const ButtonSnippetsStateColor: typeof import("../components/Button/Snippets/StateColor.vue")['default']
export const DropdownSnippetsDefault: typeof import("../components/Dropdown/Snippets/Default.vue")['default']
export const DropdownSnippetsNoIcon: typeof import("../components/Dropdown/Snippets/NoIcon.vue")['default']
export const DropdownSnippetsOnlyHeading: typeof import("../components/Dropdown/Snippets/OnlyHeading.vue")['default']
export const DropdownSnippetsProfile: typeof import("../components/Dropdown/Snippets/Profile.vue")['default']
export const DropdownSnippetsWithIcon: typeof import("../components/Dropdown/Snippets/WithIcon.vue")['default']
export const FooterSnippetsAppsmith: typeof import("../components/Footer/Snippets/Appsmith.vue")['default']
export const FooterSnippetsDefault: typeof import("../components/Footer/Snippets/Default.vue")['default']
export const FooterSnippetsLogoSection: typeof import("../components/Footer/Snippets/LogoSection.vue")['default']
export const FooterSnippetsTwoRow: typeof import("../components/Footer/Snippets/TwoRow.vue")['default']
export const FormSnippetsDefault: typeof import("../components/Form/Snippets/Default.vue")['default']
export const FormSnippetsElement: typeof import("../components/Form/Snippets/Element.vue")['default']
export const FormSnippetsFloatinglabel: typeof import("../components/Form/Snippets/Floatinglabel.vue")['default']
export const PaginationSnippetsDefault: typeof import("../components/Pagination/Snippets/Default.vue")['default']
export const PaginationSnippetsWithArrow: typeof import("../components/Pagination/Snippets/WithArrow.vue")['default']
export const RatingSnippetsDefault: typeof import("../components/Rating/Snippets/Default.vue")['default']
export const RatingSnippetsHeart: typeof import("../components/Rating/Snippets/Heart.vue")['default']
export const RatingSnippetsImdb: typeof import("../components/Rating/Snippets/Imdb.vue")['default']
export const RatingSnippetsOurCard: typeof import("../components/Rating/Snippets/OurCard.vue")['default']
export const RatingSnippetsSmiley: typeof import("../components/Rating/Snippets/Smiley.vue")['default']
export const RatingSnippetsYesOrNo: typeof import("../components/Rating/Snippets/YesOrNo.vue")['default']
export const SidebarSnippetsDefault: typeof import("../components/Sidebar/Snippets/Default.vue")['default']
export const SidebarSnippetsSectioned: typeof import("../components/Sidebar/Snippets/Sectioned.vue")['default']
export const SidebarSnippetsSeparator: typeof import("../components/Sidebar/Snippets/Separator.vue")['default']
export const SidebarSnippetsWithBadge: typeof import("../components/Sidebar/Snippets/WithBadge.vue")['default']
export const ToastSnippetsDefault: typeof import("../components/Toast/Snippets/Default.vue")['default']
export const ToastSnippetsOutline: typeof import("../components/Toast/Snippets/Outline.vue")['default']
export const ToastSnippetsSolidColor: typeof import("../components/Toast/Snippets/SolidColor.vue")['default']
export const ToastSnippetsStateColor: typeof import("../components/Toast/Snippets/StateColor.vue")['default']
export const ToastSnippetsWithButton: typeof import("../components/Toast/Snippets/WithButton.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyAlertInfo: typeof import("../components/Alert/AlertInfo.vue")['default']
export const LazyAlertBorderLeft: typeof import("../components/Alert/BorderLeft.vue")['default']
export const LazyAlertDefaultAlert: typeof import("../components/Alert/DefaultAlert.vue")['default']
export const LazyAlertStateAlert: typeof import("../components/Alert/StateAlert.vue")['default']
export const LazyAlertWithBorder: typeof import("../components/Alert/WithBorder.vue")['default']
export const LazyAlertWithButton: typeof import("../components/Alert/WithButton.vue")['default']
export const LazyAlertWithIcon: typeof import("../components/Alert/WithIcon.vue")['default']
export const LazyAlertWithLink: typeof import("../components/Alert/WithLink.vue")['default']
export const LazyBadgeCancel: typeof import("../components/Badge/Cancel.vue")['default']
export const LazyBadgeDefault: typeof import("../components/Badge/Default.vue")['default']
export const LazyBadgeIcon: typeof import("../components/Badge/Icon.vue")['default']
export const LazyBadgeLarge: typeof import("../components/Badge/Large.vue")['default']
export const LazyBadgeLink: typeof import("../components/Badge/Link.vue")['default']
export const LazyBadgeOutline: typeof import("../components/Badge/Outline.vue")['default']
export const LazyBadgePill: typeof import("../components/Badge/Pill.vue")['default']
export const LazyBadgePillOutline: typeof import("../components/Badge/PillOutline.vue")['default']
export const LazyBadgePositioned: typeof import("../components/Badge/Positioned.vue")['default']
export const LazyBadgeRectangle: typeof import("../components/Badge/Rectangle.vue")['default']
export const LazyBadgeSize: typeof import("../components/Badge/Size.vue")['default']
export const LazyBadgeStateColor: typeof import("../components/Badge/StateColor.vue")['default']
export const LazyBadgeText: typeof import("../components/Badge/Text.vue")['default']
export const LazyAvatarBadge: typeof import("../components/Avatar/Badge.vue")['default']
export const LazyAvatarCircle: typeof import("../components/Avatar/Circle.vue")['default']
export const LazyAvatarColor: typeof import("../components/Avatar/Color.vue")['default']
export const LazyAvatarDefault: typeof import("../components/Avatar/Default.vue")['default']
export const LazyAvatarDropDown: typeof import("../components/Avatar/DropDown.vue")['default']
export const LazyAvatarGroup1: typeof import("../components/Avatar/Group1.vue")['default']
export const LazyAvatarGroup2: typeof import("../components/Avatar/Group2.vue")['default']
export const LazyAvatarInfo: typeof import("../components/Avatar/Info.vue")['default']
export const LazyAvatarPresence: typeof import("../components/Avatar/Presence.vue")['default']
export const LazyAvatarPresenceRing: typeof import("../components/Avatar/PresenceRing.vue")['default']
export const LazyAvatarShadow: typeof import("../components/Avatar/Shadow.vue")['default']
export const LazyAvatarSize: typeof import("../components/Avatar/Size.vue")['default']
export const LazyAvatarSquare: typeof import("../components/Avatar/Square.vue")['default']
export const LazyBreadCrumbAlignment: typeof import("../components/BreadCrumb/Alignment.vue")['default']
export const LazyBreadCrumbArrow: typeof import("../components/BreadCrumb/Arrow.vue")['default']
export const LazyBreadCrumbDefault: typeof import("../components/BreadCrumb/Default.vue")['default']
export const LazyBreadCrumbIcon: typeof import("../components/BreadCrumb/Icon.vue")['default']
export const LazyBreadCrumbOutline: typeof import("../components/BreadCrumb/Outline.vue")['default']
export const LazyBreadCrumbSeparator: typeof import("../components/BreadCrumb/Separator.vue")['default']
export const LazyBreadCrumbSolid: typeof import("../components/BreadCrumb/Solid.vue")['default']
export const LazyCodeHighlight: typeof import("../components/CodeSnippet/CodeHighlight.vue")['default']
export const LazyButtonAppsmith: typeof import("../components/Button/Appsmith.vue")['default']
export const LazyButtonBlockButtons: typeof import("../components/Button/BlockButtons.vue")['default']
export const LazyButtonInfo: typeof import("../components/Button/ButtonInfo.vue")['default']
export const LazyButtonColoredShadow: typeof import("../components/Button/ColoredShadow.vue")['default']
export const LazyButtonDarkColor: typeof import("../components/Button/DarkColor.vue")['default']
export const LazyButtonDefault: typeof import("../components/Button/Default.vue")['default']
export const LazyButtonDualIcon: typeof import("../components/Button/DualIcon.vue")['default']
export const LazyButtonGradient: typeof import("../components/Button/Gradient.vue")['default']
export const LazyButtonLightColor: typeof import("../components/Button/LightColor.vue")['default']
export const LazyButtonOutline: typeof import("../components/Button/Outline.vue")['default']
export const LazyButtonSize: typeof import("../components/Button/Size.vue")['default']
export const LazyButtonStateColor: typeof import("../components/Button/StateColor.vue")['default']
export const LazyDropdownDefault: typeof import("../components/Dropdown/Default.vue")['default']
export const LazyDropdownDropDownInfo: typeof import("../components/Dropdown/DropDownInfo.vue")['default']
export const LazyDropdownNoIcon: typeof import("../components/Dropdown/NoIcon.vue")['default']
export const LazyDropdownOnlyHeading: typeof import("../components/Dropdown/OnlyHeading.vue")['default']
export const LazyDropdownProfile: typeof import("../components/Dropdown/Profile.vue")['default']
export const LazyDropdownWithIcon: typeof import("../components/Dropdown/WithIcon.vue")['default']
export const LazyFooterAppsmith: typeof import("../components/Footer/Appsmith.vue")['default']
export const LazyFooterDefault: typeof import("../components/Footer/Default.vue")['default']
export const LazyFooterInfo: typeof import("../components/Footer/FooterInfo.vue")['default']
export const LazyFooterLogoSection: typeof import("../components/Footer/LogoSection.vue")['default']
export const LazyFooterTwoRow: typeof import("../components/Footer/TwoRow.vue")['default']
export const LazyFormDefault: typeof import("../components/Form/Default.vue")['default']
export const LazyFormElement: typeof import("../components/Form/Element.vue")['default']
export const LazyFormFloatinglabel: typeof import("../components/Form/Floatinglabel.vue")['default']
export const LazyFormInfo: typeof import("../components/Form/FormInfo.vue")['default']
export const LazyHeadersHeading: typeof import("../components/Headers/Heading.vue")['default']
export const LazyHeadersSubHeading: typeof import("../components/Headers/SubHeading.vue")['default']
export const LazyNavigationMenuItems: typeof import("../components/Navigation/MenuItems.js")['default']
export const LazyPaginationDefault: typeof import("../components/Pagination/Default.vue")['default']
export const LazyPaginationInfo: typeof import("../components/Pagination/PaginationInfo.vue")['default']
export const LazyPaginationWithArrow: typeof import("../components/Pagination/WithArrow.vue")['default']
export const LazyRatingDefault: typeof import("../components/Rating/Default.vue")['default']
export const LazyRatingHeart: typeof import("../components/Rating/Heart.vue")['default']
export const LazyRatingImdb: typeof import("../components/Rating/Imdb.vue")['default']
export const LazyRatingOurCard: typeof import("../components/Rating/OurCard.vue")['default']
export const LazyRatingSmiley: typeof import("../components/Rating/Smiley.vue")['default']
export const LazyRatingYesOrNo: typeof import("../components/Rating/YesOrNo.vue")['default']
export const LazySidebarDefault: typeof import("../components/Sidebar/Default.vue")['default']
export const LazySidebarSectioned: typeof import("../components/Sidebar/Sectioned.vue")['default']
export const LazySidebarSeparator: typeof import("../components/Sidebar/Separator.vue")['default']
export const LazySidebarInfo: typeof import("../components/Sidebar/SidebarInfo.vue")['default']
export const LazySidebarWithBadge: typeof import("../components/Sidebar/WithBadge.vue")['default']
export const LazyToastDefault: typeof import("../components/Toast/Default.vue")['default']
export const LazyToastOutline: typeof import("../components/Toast/Outline.vue")['default']
export const LazyToastSolidColor: typeof import("../components/Toast/SolidColor.vue")['default']
export const LazyToastStateColor: typeof import("../components/Toast/StateColor.vue")['default']
export const LazyToastInfo: typeof import("../components/Toast/ToastInfo.vue")['default']
export const LazyToastWithButton: typeof import("../components/Toast/WithButton.vue")['default']
export const LazyUtilsComponentPad: typeof import("../components/Utils/ComponentPad.vue")['default']
export const LazyUtilsCopyButton: typeof import("../components/Utils/CopyButton.vue")['default']
export const LazyUtilsHideCodeButton: typeof import("../components/Utils/HideCodeButton.vue")['default']
export const LazyUtilsShowCodeButton: typeof import("../components/Utils/ShowCodeButton.vue")['default']
export const LazyUtilsToast: typeof import("../components/Utils/Toast.vue")['default']
export const LazyAlertSnippetsBorderLeft: typeof import("../components/Alert/Snippets/BorderLeft.vue")['default']
export const LazyAlertSnippetsDefaultAlert: typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default']
export const LazyAlertSnippetsStateAlert: typeof import("../components/Alert/Snippets/StateAlert.vue")['default']
export const LazyAlertSnippetsWithBorder: typeof import("../components/Alert/Snippets/WithBorder.vue")['default']
export const LazyAlertSnippetsWithButton: typeof import("../components/Alert/Snippets/WithButton.vue")['default']
export const LazyAlertSnippetsWithIcon: typeof import("../components/Alert/Snippets/WithIcon.vue")['default']
export const LazyAlertSnippetsWithLink: typeof import("../components/Alert/Snippets/WithLink.vue")['default']
export const LazyBadgeSnippetsCancel: typeof import("../components/Badge/Snippets/Cancel.vue")['default']
export const LazyBadgeSnippetsDefault: typeof import("../components/Badge/Snippets/default.vue")['default']
export const LazyBadgeSnippetsIcon: typeof import("../components/Badge/Snippets/Icon.vue")['default']
export const LazyBadgeSnippetsLarge: typeof import("../components/Badge/Snippets/Large.vue")['default']
export const LazyBadgeSnippetsLink: typeof import("../components/Badge/Snippets/Link.vue")['default']
export const LazyBadgeSnippetsOutline: typeof import("../components/Badge/Snippets/Outline.vue")['default']
export const LazyBadgeSnippetsPill: typeof import("../components/Badge/Snippets/Pill.vue")['default']
export const LazyBadgeSnippetsPillOutline: typeof import("../components/Badge/Snippets/PillOutline.vue")['default']
export const LazyBadgeSnippetsPositioned: typeof import("../components/Badge/Snippets/Positioned.vue")['default']
export const LazyBadgeSnippetsRectangle: typeof import("../components/Badge/Snippets/Rectangle.vue")['default']
export const LazyBadgeSnippetsSize: typeof import("../components/Badge/Snippets/Size.vue")['default']
export const LazyBadgeSnippetsStateColor: typeof import("../components/Badge/Snippets/StateColor.vue")['default']
export const LazyBadgeSnippetsText: typeof import("../components/Badge/Snippets/Text.vue")['default']
export const LazyAvatarSnippetsBadge: typeof import("../components/Avatar/Snippets/Badge.vue")['default']
export const LazyAvatarSnippetsCircle: typeof import("../components/Avatar/Snippets/Circle.vue")['default']
export const LazyAvatarSnippetsColor: typeof import("../components/Avatar/Snippets/Color.vue")['default']
export const LazyAvatarSnippetsDefault: typeof import("../components/Avatar/Snippets/Default.vue")['default']
export const LazyAvatarSnippetsDropDown: typeof import("../components/Avatar/Snippets/DropDown.vue")['default']
export const LazyAvatarSnippetsGroup1: typeof import("../components/Avatar/Snippets/Group1.vue")['default']
export const LazyAvatarSnippetsGroup2: typeof import("../components/Avatar/Snippets/Group2.vue")['default']
export const LazyAvatarSnippetsInfo: typeof import("../components/Avatar/Snippets/Info.vue")['default']
export const LazyAvatarSnippetsPresence: typeof import("../components/Avatar/Snippets/Presence.vue")['default']
export const LazyAvatarSnippetsPresenceRing: typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default']
export const LazyAvatarSnippetsShadow: typeof import("../components/Avatar/Snippets/Shadow.vue")['default']
export const LazyAvatarSnippetsSize: typeof import("../components/Avatar/Snippets/Size.vue")['default']
export const LazyAvatarSnippetsSquare: typeof import("../components/Avatar/Snippets/Square.vue")['default']
export const LazyBreadCrumbSnippetsAlignment: typeof import("../components/BreadCrumb/Snippets/Alignment.vue")['default']
export const LazyBreadCrumbSnippetsArrow: typeof import("../components/BreadCrumb/Snippets/Arrow.vue")['default']
export const LazyBreadCrumbSnippetsDefault: typeof import("../components/BreadCrumb/Snippets/Default.vue")['default']
export const LazyBreadCrumbSnippetsIcon: typeof import("../components/BreadCrumb/Snippets/Icon.vue")['default']
export const LazyBreadCrumbSnippetsOutline: typeof import("../components/BreadCrumb/Snippets/Outline.vue")['default']
export const LazyBreadCrumbSnippetsSeparator: typeof import("../components/BreadCrumb/Snippets/Separator.vue")['default']
export const LazyBreadCrumbSnippetsSolid: typeof import("../components/BreadCrumb/Snippets/Solid.vue")['default']
export const LazyButtonSnippetsAppsmith: typeof import("../components/Button/Snippets/Appsmith.vue")['default']
export const LazyButtonSnippetsBlockButtons: typeof import("../components/Button/Snippets/BlockButtons.vue")['default']
export const LazyButtonSnippetsColoredShadow: typeof import("../components/Button/Snippets/ColoredShadow.vue")['default']
export const LazyButtonSnippetsDarkColor: typeof import("../components/Button/Snippets/DarkColor.vue")['default']
export const LazyButtonSnippetsDefault: typeof import("../components/Button/Snippets/Default.vue")['default']
export const LazyButtonSnippetsDualIcon: typeof import("../components/Button/Snippets/DualIcon.vue")['default']
export const LazyButtonSnippetsGradient: typeof import("../components/Button/Snippets/Gradient.vue")['default']
export const LazyButtonSnippetsLightColor: typeof import("../components/Button/Snippets/LightColor.vue")['default']
export const LazyButtonSnippetsOutline: typeof import("../components/Button/Snippets/Outline.vue")['default']
export const LazyButtonSnippetsSize: typeof import("../components/Button/Snippets/Size.vue")['default']
export const LazyButtonSnippetsStateColor: typeof import("../components/Button/Snippets/StateColor.vue")['default']
export const LazyDropdownSnippetsDefault: typeof import("../components/Dropdown/Snippets/Default.vue")['default']
export const LazyDropdownSnippetsNoIcon: typeof import("../components/Dropdown/Snippets/NoIcon.vue")['default']
export const LazyDropdownSnippetsOnlyHeading: typeof import("../components/Dropdown/Snippets/OnlyHeading.vue")['default']
export const LazyDropdownSnippetsProfile: typeof import("../components/Dropdown/Snippets/Profile.vue")['default']
export const LazyDropdownSnippetsWithIcon: typeof import("../components/Dropdown/Snippets/WithIcon.vue")['default']
export const LazyFooterSnippetsAppsmith: typeof import("../components/Footer/Snippets/Appsmith.vue")['default']
export const LazyFooterSnippetsDefault: typeof import("../components/Footer/Snippets/Default.vue")['default']
export const LazyFooterSnippetsLogoSection: typeof import("../components/Footer/Snippets/LogoSection.vue")['default']
export const LazyFooterSnippetsTwoRow: typeof import("../components/Footer/Snippets/TwoRow.vue")['default']
export const LazyFormSnippetsDefault: typeof import("../components/Form/Snippets/Default.vue")['default']
export const LazyFormSnippetsElement: typeof import("../components/Form/Snippets/Element.vue")['default']
export const LazyFormSnippetsFloatinglabel: typeof import("../components/Form/Snippets/Floatinglabel.vue")['default']
export const LazyPaginationSnippetsDefault: typeof import("../components/Pagination/Snippets/Default.vue")['default']
export const LazyPaginationSnippetsWithArrow: typeof import("../components/Pagination/Snippets/WithArrow.vue")['default']
export const LazyRatingSnippetsDefault: typeof import("../components/Rating/Snippets/Default.vue")['default']
export const LazyRatingSnippetsHeart: typeof import("../components/Rating/Snippets/Heart.vue")['default']
export const LazyRatingSnippetsImdb: typeof import("../components/Rating/Snippets/Imdb.vue")['default']
export const LazyRatingSnippetsOurCard: typeof import("../components/Rating/Snippets/OurCard.vue")['default']
export const LazyRatingSnippetsSmiley: typeof import("../components/Rating/Snippets/Smiley.vue")['default']
export const LazyRatingSnippetsYesOrNo: typeof import("../components/Rating/Snippets/YesOrNo.vue")['default']
export const LazySidebarSnippetsDefault: typeof import("../components/Sidebar/Snippets/Default.vue")['default']
export const LazySidebarSnippetsSectioned: typeof import("../components/Sidebar/Snippets/Sectioned.vue")['default']
export const LazySidebarSnippetsSeparator: typeof import("../components/Sidebar/Snippets/Separator.vue")['default']
export const LazySidebarSnippetsWithBadge: typeof import("../components/Sidebar/Snippets/WithBadge.vue")['default']
export const LazyToastSnippetsDefault: typeof import("../components/Toast/Snippets/Default.vue")['default']
export const LazyToastSnippetsOutline: typeof import("../components/Toast/Snippets/Outline.vue")['default']
export const LazyToastSnippetsSolidColor: typeof import("../components/Toast/Snippets/SolidColor.vue")['default']
export const LazyToastSnippetsStateColor: typeof import("../components/Toast/Snippets/StateColor.vue")['default']
export const LazyToastSnippetsWithButton: typeof import("../components/Toast/Snippets/WithButton.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
