// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import("../components/Footer.vue")['default'],
    'Header': typeof import("../components/Header.vue")['default'],
    'AlertInfo': typeof import("../components/Alert/AlertInfo.vue")['default'],
    'AlertWithLink': typeof import("../components/Alert/AlertWithLink.vue")['default'],
    'AlertBorderLeft': typeof import("../components/Alert/BorderLeft.vue")['default'],
    'AlertDefaultAlert': typeof import("../components/Alert/DefaultAlert.vue")['default'],
    'AlertStateAlert': typeof import("../components/Alert/StateAlert.vue")['default'],
    'AlertWithBorder': typeof import("../components/Alert/WithBorder.vue")['default'],
    'AlertWithButton': typeof import("../components/Alert/WithButton.vue")['default'],
    'AlertWithIcon': typeof import("../components/Alert/WithIcon.vue")['default'],
    'AvatarBadge': typeof import("../components/Avatar/Badge.vue")['default'],
    'AvatarCircle': typeof import("../components/Avatar/Circle.vue")['default'],
    'AvatarColor': typeof import("../components/Avatar/Color.vue")['default'],
    'AvatarDefault': typeof import("../components/Avatar/Default.vue")['default'],
    'AvatarDropDown': typeof import("../components/Avatar/DropDown.vue")['default'],
    'AvatarGroup1': typeof import("../components/Avatar/Group1.vue")['default'],
    'AvatarGroup2': typeof import("../components/Avatar/Group2.vue")['default'],
    'AvatarInfo': typeof import("../components/Avatar/Info.vue")['default'],
    'AvatarPresence': typeof import("../components/Avatar/Presence.vue")['default'],
    'AvatarPresenceRing': typeof import("../components/Avatar/PresenceRing.vue")['default'],
    'AvatarShadow': typeof import("../components/Avatar/Shadow.vue")['default'],
    'AvatarSize': typeof import("../components/Avatar/Size.vue")['default'],
    'AvatarSquare': typeof import("../components/Avatar/Square.vue")['default'],
    'CodeHighlight': typeof import("../components/CodeSnippet/CodeHighlight.vue")['default'],
    'BadgeCancel': typeof import("../components/Badge/Cancel.vue")['default'],
    'BadgeDefault': typeof import("../components/Badge/Default.vue")['default'],
    'BadgeIcon': typeof import("../components/Badge/Icon.vue")['default'],
    'BadgeLarge': typeof import("../components/Badge/Large.vue")['default'],
    'BadgeLink': typeof import("../components/Badge/Link.vue")['default'],
    'BadgeOutline': typeof import("../components/Badge/Outline.vue")['default'],
    'BadgePill': typeof import("../components/Badge/Pill.vue")['default'],
    'BadgePillOutline': typeof import("../components/Badge/PillOutline.vue")['default'],
    'BadgePositioned': typeof import("../components/Badge/Positioned.vue")['default'],
    'BadgeRectangle': typeof import("../components/Badge/Rectangle.vue")['default'],
    'BadgeSize': typeof import("../components/Badge/Size.vue")['default'],
    'BadgeStateColor': typeof import("../components/Badge/StateColor.vue")['default'],
    'BadgeText': typeof import("../components/Badge/Text.vue")['default'],
    'HeadersHeading': typeof import("../components/Headers/Heading.vue")['default'],
    'HeadersSubHeading': typeof import("../components/Headers/SubHeading.vue")['default'],
    'NavigationMenuItems': typeof import("../components/Navigation/MenuItems.js")['default'],
    'UtilsComponentPad': typeof import("../components/Utils/ComponentPad.vue")['default'],
    'UtilsCopyButton': typeof import("../components/Utils/CopyButton.vue")['default'],
    'UtilsHideCodeButton': typeof import("../components/Utils/HideCodeButton.vue")['default'],
    'UtilsShowCodeButton': typeof import("../components/Utils/ShowCodeButton.vue")['default'],
    'UtilsToast': typeof import("../components/Utils/Toast.vue")['default'],
    'AlertSnippetsBorderLeft': typeof import("../components/Alert/Snippets/BorderLeft.vue")['default'],
    'AlertSnippetsDefaultAlert': typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default'],
    'AlertSnippetsStateAlert': typeof import("../components/Alert/Snippets/StateAlert.vue")['default'],
    'AlertSnippetsWithBorder': typeof import("../components/Alert/Snippets/WithBorder.vue")['default'],
    'AlertSnippetsWithButton': typeof import("../components/Alert/Snippets/WithButton.vue")['default'],
    'AlertSnippetsWithIcon': typeof import("../components/Alert/Snippets/WithIcon.vue")['default'],
    'AlertSnippetsWithLink': typeof import("../components/Alert/Snippets/WithLink.vue")['default'],
    'AvatarSnippetsBadge': typeof import("../components/Avatar/Snippets/Badge.vue")['default'],
    'AvatarSnippetsCircle': typeof import("../components/Avatar/Snippets/Circle.vue")['default'],
    'AvatarSnippetsColor': typeof import("../components/Avatar/Snippets/Color.vue")['default'],
    'AvatarSnippetsDefault': typeof import("../components/Avatar/Snippets/Default.vue")['default'],
    'AvatarSnippetsDropDown': typeof import("../components/Avatar/Snippets/DropDown.vue")['default'],
    'AvatarSnippetsGroup1': typeof import("../components/Avatar/Snippets/Group1.vue")['default'],
    'AvatarSnippetsGroup2': typeof import("../components/Avatar/Snippets/Group2.vue")['default'],
    'AvatarSnippetsInfo': typeof import("../components/Avatar/Snippets/Info.vue")['default'],
    'AvatarSnippetsPresence': typeof import("../components/Avatar/Snippets/Presence.vue")['default'],
    'AvatarSnippetsPresenceRing': typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default'],
    'AvatarSnippetsShadow': typeof import("../components/Avatar/Snippets/Shadow.vue")['default'],
    'AvatarSnippetsSize': typeof import("../components/Avatar/Snippets/Size.vue")['default'],
    'AvatarSnippetsSquare': typeof import("../components/Avatar/Snippets/Square.vue")['default'],
    'BadgeSnippetsCancel': typeof import("../components/Badge/Snippets/Cancel.vue")['default'],
    'BadgeSnippetsDefault': typeof import("../components/Badge/Snippets/default.vue")['default'],
    'BadgeSnippetsIcon': typeof import("../components/Badge/Snippets/Icon.vue")['default'],
    'BadgeSnippetsLarge': typeof import("../components/Badge/Snippets/Large.vue")['default'],
    'BadgeSnippetsLink': typeof import("../components/Badge/Snippets/Link.vue")['default'],
    'BadgeSnippetsOutline': typeof import("../components/Badge/Snippets/Outline.vue")['default'],
    'BadgeSnippetsPill': typeof import("../components/Badge/Snippets/Pill.vue")['default'],
    'BadgeSnippetsPillOutline': typeof import("../components/Badge/Snippets/PillOutline.vue")['default'],
    'BadgeSnippetsPositioned': typeof import("../components/Badge/Snippets/Positioned.vue")['default'],
    'BadgeSnippetsRectangle': typeof import("../components/Badge/Snippets/Rectangle.vue")['default'],
    'BadgeSnippetsSize': typeof import("../components/Badge/Snippets/Size.vue")['default'],
    'BadgeSnippetsStateColor': typeof import("../components/Badge/Snippets/StateColor.vue")['default'],
    'BadgeSnippetsText': typeof import("../components/Badge/Snippets/Text.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyHeader': typeof import("../components/Header.vue")['default'],
    'LazyAlertInfo': typeof import("../components/Alert/AlertInfo.vue")['default'],
    'LazyAlertWithLink': typeof import("../components/Alert/AlertWithLink.vue")['default'],
    'LazyAlertBorderLeft': typeof import("../components/Alert/BorderLeft.vue")['default'],
    'LazyAlertDefaultAlert': typeof import("../components/Alert/DefaultAlert.vue")['default'],
    'LazyAlertStateAlert': typeof import("../components/Alert/StateAlert.vue")['default'],
    'LazyAlertWithBorder': typeof import("../components/Alert/WithBorder.vue")['default'],
    'LazyAlertWithButton': typeof import("../components/Alert/WithButton.vue")['default'],
    'LazyAlertWithIcon': typeof import("../components/Alert/WithIcon.vue")['default'],
    'LazyAvatarBadge': typeof import("../components/Avatar/Badge.vue")['default'],
    'LazyAvatarCircle': typeof import("../components/Avatar/Circle.vue")['default'],
    'LazyAvatarColor': typeof import("../components/Avatar/Color.vue")['default'],
    'LazyAvatarDefault': typeof import("../components/Avatar/Default.vue")['default'],
    'LazyAvatarDropDown': typeof import("../components/Avatar/DropDown.vue")['default'],
    'LazyAvatarGroup1': typeof import("../components/Avatar/Group1.vue")['default'],
    'LazyAvatarGroup2': typeof import("../components/Avatar/Group2.vue")['default'],
    'LazyAvatarInfo': typeof import("../components/Avatar/Info.vue")['default'],
    'LazyAvatarPresence': typeof import("../components/Avatar/Presence.vue")['default'],
    'LazyAvatarPresenceRing': typeof import("../components/Avatar/PresenceRing.vue")['default'],
    'LazyAvatarShadow': typeof import("../components/Avatar/Shadow.vue")['default'],
    'LazyAvatarSize': typeof import("../components/Avatar/Size.vue")['default'],
    'LazyAvatarSquare': typeof import("../components/Avatar/Square.vue")['default'],
    'LazyCodeHighlight': typeof import("../components/CodeSnippet/CodeHighlight.vue")['default'],
    'LazyBadgeCancel': typeof import("../components/Badge/Cancel.vue")['default'],
    'LazyBadgeDefault': typeof import("../components/Badge/Default.vue")['default'],
    'LazyBadgeIcon': typeof import("../components/Badge/Icon.vue")['default'],
    'LazyBadgeLarge': typeof import("../components/Badge/Large.vue")['default'],
    'LazyBadgeLink': typeof import("../components/Badge/Link.vue")['default'],
    'LazyBadgeOutline': typeof import("../components/Badge/Outline.vue")['default'],
    'LazyBadgePill': typeof import("../components/Badge/Pill.vue")['default'],
    'LazyBadgePillOutline': typeof import("../components/Badge/PillOutline.vue")['default'],
    'LazyBadgePositioned': typeof import("../components/Badge/Positioned.vue")['default'],
    'LazyBadgeRectangle': typeof import("../components/Badge/Rectangle.vue")['default'],
    'LazyBadgeSize': typeof import("../components/Badge/Size.vue")['default'],
    'LazyBadgeStateColor': typeof import("../components/Badge/StateColor.vue")['default'],
    'LazyBadgeText': typeof import("../components/Badge/Text.vue")['default'],
    'LazyHeadersHeading': typeof import("../components/Headers/Heading.vue")['default'],
    'LazyHeadersSubHeading': typeof import("../components/Headers/SubHeading.vue")['default'],
    'LazyNavigationMenuItems': typeof import("../components/Navigation/MenuItems.js")['default'],
    'LazyUtilsComponentPad': typeof import("../components/Utils/ComponentPad.vue")['default'],
    'LazyUtilsCopyButton': typeof import("../components/Utils/CopyButton.vue")['default'],
    'LazyUtilsHideCodeButton': typeof import("../components/Utils/HideCodeButton.vue")['default'],
    'LazyUtilsShowCodeButton': typeof import("../components/Utils/ShowCodeButton.vue")['default'],
    'LazyUtilsToast': typeof import("../components/Utils/Toast.vue")['default'],
    'LazyAlertSnippetsBorderLeft': typeof import("../components/Alert/Snippets/BorderLeft.vue")['default'],
    'LazyAlertSnippetsDefaultAlert': typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default'],
    'LazyAlertSnippetsStateAlert': typeof import("../components/Alert/Snippets/StateAlert.vue")['default'],
    'LazyAlertSnippetsWithBorder': typeof import("../components/Alert/Snippets/WithBorder.vue")['default'],
    'LazyAlertSnippetsWithButton': typeof import("../components/Alert/Snippets/WithButton.vue")['default'],
    'LazyAlertSnippetsWithIcon': typeof import("../components/Alert/Snippets/WithIcon.vue")['default'],
    'LazyAlertSnippetsWithLink': typeof import("../components/Alert/Snippets/WithLink.vue")['default'],
    'LazyAvatarSnippetsBadge': typeof import("../components/Avatar/Snippets/Badge.vue")['default'],
    'LazyAvatarSnippetsCircle': typeof import("../components/Avatar/Snippets/Circle.vue")['default'],
    'LazyAvatarSnippetsColor': typeof import("../components/Avatar/Snippets/Color.vue")['default'],
    'LazyAvatarSnippetsDefault': typeof import("../components/Avatar/Snippets/Default.vue")['default'],
    'LazyAvatarSnippetsDropDown': typeof import("../components/Avatar/Snippets/DropDown.vue")['default'],
    'LazyAvatarSnippetsGroup1': typeof import("../components/Avatar/Snippets/Group1.vue")['default'],
    'LazyAvatarSnippetsGroup2': typeof import("../components/Avatar/Snippets/Group2.vue")['default'],
    'LazyAvatarSnippetsInfo': typeof import("../components/Avatar/Snippets/Info.vue")['default'],
    'LazyAvatarSnippetsPresence': typeof import("../components/Avatar/Snippets/Presence.vue")['default'],
    'LazyAvatarSnippetsPresenceRing': typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default'],
    'LazyAvatarSnippetsShadow': typeof import("../components/Avatar/Snippets/Shadow.vue")['default'],
    'LazyAvatarSnippetsSize': typeof import("../components/Avatar/Snippets/Size.vue")['default'],
    'LazyAvatarSnippetsSquare': typeof import("../components/Avatar/Snippets/Square.vue")['default'],
    'LazyBadgeSnippetsCancel': typeof import("../components/Badge/Snippets/Cancel.vue")['default'],
    'LazyBadgeSnippetsDefault': typeof import("../components/Badge/Snippets/default.vue")['default'],
    'LazyBadgeSnippetsIcon': typeof import("../components/Badge/Snippets/Icon.vue")['default'],
    'LazyBadgeSnippetsLarge': typeof import("../components/Badge/Snippets/Large.vue")['default'],
    'LazyBadgeSnippetsLink': typeof import("../components/Badge/Snippets/Link.vue")['default'],
    'LazyBadgeSnippetsOutline': typeof import("../components/Badge/Snippets/Outline.vue")['default'],
    'LazyBadgeSnippetsPill': typeof import("../components/Badge/Snippets/Pill.vue")['default'],
    'LazyBadgeSnippetsPillOutline': typeof import("../components/Badge/Snippets/PillOutline.vue")['default'],
    'LazyBadgeSnippetsPositioned': typeof import("../components/Badge/Snippets/Positioned.vue")['default'],
    'LazyBadgeSnippetsRectangle': typeof import("../components/Badge/Snippets/Rectangle.vue")['default'],
    'LazyBadgeSnippetsSize': typeof import("../components/Badge/Snippets/Size.vue")['default'],
    'LazyBadgeSnippetsStateColor': typeof import("../components/Badge/Snippets/StateColor.vue")['default'],
    'LazyBadgeSnippetsText': typeof import("../components/Badge/Snippets/Text.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const AlertInfo: typeof import("../components/Alert/AlertInfo.vue")['default']
export const AlertWithLink: typeof import("../components/Alert/AlertWithLink.vue")['default']
export const AlertBorderLeft: typeof import("../components/Alert/BorderLeft.vue")['default']
export const AlertDefaultAlert: typeof import("../components/Alert/DefaultAlert.vue")['default']
export const AlertStateAlert: typeof import("../components/Alert/StateAlert.vue")['default']
export const AlertWithBorder: typeof import("../components/Alert/WithBorder.vue")['default']
export const AlertWithButton: typeof import("../components/Alert/WithButton.vue")['default']
export const AlertWithIcon: typeof import("../components/Alert/WithIcon.vue")['default']
export const AvatarBadge: typeof import("../components/Avatar/Badge.vue")['default']
export const AvatarCircle: typeof import("../components/Avatar/Circle.vue")['default']
export const AvatarColor: typeof import("../components/Avatar/Color.vue")['default']
export const AvatarDefault: typeof import("../components/Avatar/Default.vue")['default']
export const AvatarDropDown: typeof import("../components/Avatar/DropDown.vue")['default']
export const AvatarGroup1: typeof import("../components/Avatar/Group1.vue")['default']
export const AvatarGroup2: typeof import("../components/Avatar/Group2.vue")['default']
export const AvatarInfo: typeof import("../components/Avatar/Info.vue")['default']
export const AvatarPresence: typeof import("../components/Avatar/Presence.vue")['default']
export const AvatarPresenceRing: typeof import("../components/Avatar/PresenceRing.vue")['default']
export const AvatarShadow: typeof import("../components/Avatar/Shadow.vue")['default']
export const AvatarSize: typeof import("../components/Avatar/Size.vue")['default']
export const AvatarSquare: typeof import("../components/Avatar/Square.vue")['default']
export const CodeHighlight: typeof import("../components/CodeSnippet/CodeHighlight.vue")['default']
export const BadgeCancel: typeof import("../components/Badge/Cancel.vue")['default']
export const BadgeDefault: typeof import("../components/Badge/Default.vue")['default']
export const BadgeIcon: typeof import("../components/Badge/Icon.vue")['default']
export const BadgeLarge: typeof import("../components/Badge/Large.vue")['default']
export const BadgeLink: typeof import("../components/Badge/Link.vue")['default']
export const BadgeOutline: typeof import("../components/Badge/Outline.vue")['default']
export const BadgePill: typeof import("../components/Badge/Pill.vue")['default']
export const BadgePillOutline: typeof import("../components/Badge/PillOutline.vue")['default']
export const BadgePositioned: typeof import("../components/Badge/Positioned.vue")['default']
export const BadgeRectangle: typeof import("../components/Badge/Rectangle.vue")['default']
export const BadgeSize: typeof import("../components/Badge/Size.vue")['default']
export const BadgeStateColor: typeof import("../components/Badge/StateColor.vue")['default']
export const BadgeText: typeof import("../components/Badge/Text.vue")['default']
export const HeadersHeading: typeof import("../components/Headers/Heading.vue")['default']
export const HeadersSubHeading: typeof import("../components/Headers/SubHeading.vue")['default']
export const NavigationMenuItems: typeof import("../components/Navigation/MenuItems.js")['default']
export const UtilsComponentPad: typeof import("../components/Utils/ComponentPad.vue")['default']
export const UtilsCopyButton: typeof import("../components/Utils/CopyButton.vue")['default']
export const UtilsHideCodeButton: typeof import("../components/Utils/HideCodeButton.vue")['default']
export const UtilsShowCodeButton: typeof import("../components/Utils/ShowCodeButton.vue")['default']
export const UtilsToast: typeof import("../components/Utils/Toast.vue")['default']
export const AlertSnippetsBorderLeft: typeof import("../components/Alert/Snippets/BorderLeft.vue")['default']
export const AlertSnippetsDefaultAlert: typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default']
export const AlertSnippetsStateAlert: typeof import("../components/Alert/Snippets/StateAlert.vue")['default']
export const AlertSnippetsWithBorder: typeof import("../components/Alert/Snippets/WithBorder.vue")['default']
export const AlertSnippetsWithButton: typeof import("../components/Alert/Snippets/WithButton.vue")['default']
export const AlertSnippetsWithIcon: typeof import("../components/Alert/Snippets/WithIcon.vue")['default']
export const AlertSnippetsWithLink: typeof import("../components/Alert/Snippets/WithLink.vue")['default']
export const AvatarSnippetsBadge: typeof import("../components/Avatar/Snippets/Badge.vue")['default']
export const AvatarSnippetsCircle: typeof import("../components/Avatar/Snippets/Circle.vue")['default']
export const AvatarSnippetsColor: typeof import("../components/Avatar/Snippets/Color.vue")['default']
export const AvatarSnippetsDefault: typeof import("../components/Avatar/Snippets/Default.vue")['default']
export const AvatarSnippetsDropDown: typeof import("../components/Avatar/Snippets/DropDown.vue")['default']
export const AvatarSnippetsGroup1: typeof import("../components/Avatar/Snippets/Group1.vue")['default']
export const AvatarSnippetsGroup2: typeof import("../components/Avatar/Snippets/Group2.vue")['default']
export const AvatarSnippetsInfo: typeof import("../components/Avatar/Snippets/Info.vue")['default']
export const AvatarSnippetsPresence: typeof import("../components/Avatar/Snippets/Presence.vue")['default']
export const AvatarSnippetsPresenceRing: typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default']
export const AvatarSnippetsShadow: typeof import("../components/Avatar/Snippets/Shadow.vue")['default']
export const AvatarSnippetsSize: typeof import("../components/Avatar/Snippets/Size.vue")['default']
export const AvatarSnippetsSquare: typeof import("../components/Avatar/Snippets/Square.vue")['default']
export const BadgeSnippetsCancel: typeof import("../components/Badge/Snippets/Cancel.vue")['default']
export const BadgeSnippetsDefault: typeof import("../components/Badge/Snippets/default.vue")['default']
export const BadgeSnippetsIcon: typeof import("../components/Badge/Snippets/Icon.vue")['default']
export const BadgeSnippetsLarge: typeof import("../components/Badge/Snippets/Large.vue")['default']
export const BadgeSnippetsLink: typeof import("../components/Badge/Snippets/Link.vue")['default']
export const BadgeSnippetsOutline: typeof import("../components/Badge/Snippets/Outline.vue")['default']
export const BadgeSnippetsPill: typeof import("../components/Badge/Snippets/Pill.vue")['default']
export const BadgeSnippetsPillOutline: typeof import("../components/Badge/Snippets/PillOutline.vue")['default']
export const BadgeSnippetsPositioned: typeof import("../components/Badge/Snippets/Positioned.vue")['default']
export const BadgeSnippetsRectangle: typeof import("../components/Badge/Snippets/Rectangle.vue")['default']
export const BadgeSnippetsSize: typeof import("../components/Badge/Snippets/Size.vue")['default']
export const BadgeSnippetsStateColor: typeof import("../components/Badge/Snippets/StateColor.vue")['default']
export const BadgeSnippetsText: typeof import("../components/Badge/Snippets/Text.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyAlertInfo: typeof import("../components/Alert/AlertInfo.vue")['default']
export const LazyAlertWithLink: typeof import("../components/Alert/AlertWithLink.vue")['default']
export const LazyAlertBorderLeft: typeof import("../components/Alert/BorderLeft.vue")['default']
export const LazyAlertDefaultAlert: typeof import("../components/Alert/DefaultAlert.vue")['default']
export const LazyAlertStateAlert: typeof import("../components/Alert/StateAlert.vue")['default']
export const LazyAlertWithBorder: typeof import("../components/Alert/WithBorder.vue")['default']
export const LazyAlertWithButton: typeof import("../components/Alert/WithButton.vue")['default']
export const LazyAlertWithIcon: typeof import("../components/Alert/WithIcon.vue")['default']
export const LazyAvatarBadge: typeof import("../components/Avatar/Badge.vue")['default']
export const LazyAvatarCircle: typeof import("../components/Avatar/Circle.vue")['default']
export const LazyAvatarColor: typeof import("../components/Avatar/Color.vue")['default']
export const LazyAvatarDefault: typeof import("../components/Avatar/Default.vue")['default']
export const LazyAvatarDropDown: typeof import("../components/Avatar/DropDown.vue")['default']
export const LazyAvatarGroup1: typeof import("../components/Avatar/Group1.vue")['default']
export const LazyAvatarGroup2: typeof import("../components/Avatar/Group2.vue")['default']
export const LazyAvatarInfo: typeof import("../components/Avatar/Info.vue")['default']
export const LazyAvatarPresence: typeof import("../components/Avatar/Presence.vue")['default']
export const LazyAvatarPresenceRing: typeof import("../components/Avatar/PresenceRing.vue")['default']
export const LazyAvatarShadow: typeof import("../components/Avatar/Shadow.vue")['default']
export const LazyAvatarSize: typeof import("../components/Avatar/Size.vue")['default']
export const LazyAvatarSquare: typeof import("../components/Avatar/Square.vue")['default']
export const LazyCodeHighlight: typeof import("../components/CodeSnippet/CodeHighlight.vue")['default']
export const LazyBadgeCancel: typeof import("../components/Badge/Cancel.vue")['default']
export const LazyBadgeDefault: typeof import("../components/Badge/Default.vue")['default']
export const LazyBadgeIcon: typeof import("../components/Badge/Icon.vue")['default']
export const LazyBadgeLarge: typeof import("../components/Badge/Large.vue")['default']
export const LazyBadgeLink: typeof import("../components/Badge/Link.vue")['default']
export const LazyBadgeOutline: typeof import("../components/Badge/Outline.vue")['default']
export const LazyBadgePill: typeof import("../components/Badge/Pill.vue")['default']
export const LazyBadgePillOutline: typeof import("../components/Badge/PillOutline.vue")['default']
export const LazyBadgePositioned: typeof import("../components/Badge/Positioned.vue")['default']
export const LazyBadgeRectangle: typeof import("../components/Badge/Rectangle.vue")['default']
export const LazyBadgeSize: typeof import("../components/Badge/Size.vue")['default']
export const LazyBadgeStateColor: typeof import("../components/Badge/StateColor.vue")['default']
export const LazyBadgeText: typeof import("../components/Badge/Text.vue")['default']
export const LazyHeadersHeading: typeof import("../components/Headers/Heading.vue")['default']
export const LazyHeadersSubHeading: typeof import("../components/Headers/SubHeading.vue")['default']
export const LazyNavigationMenuItems: typeof import("../components/Navigation/MenuItems.js")['default']
export const LazyUtilsComponentPad: typeof import("../components/Utils/ComponentPad.vue")['default']
export const LazyUtilsCopyButton: typeof import("../components/Utils/CopyButton.vue")['default']
export const LazyUtilsHideCodeButton: typeof import("../components/Utils/HideCodeButton.vue")['default']
export const LazyUtilsShowCodeButton: typeof import("../components/Utils/ShowCodeButton.vue")['default']
export const LazyUtilsToast: typeof import("../components/Utils/Toast.vue")['default']
export const LazyAlertSnippetsBorderLeft: typeof import("../components/Alert/Snippets/BorderLeft.vue")['default']
export const LazyAlertSnippetsDefaultAlert: typeof import("../components/Alert/Snippets/DefaultAlert.vue")['default']
export const LazyAlertSnippetsStateAlert: typeof import("../components/Alert/Snippets/StateAlert.vue")['default']
export const LazyAlertSnippetsWithBorder: typeof import("../components/Alert/Snippets/WithBorder.vue")['default']
export const LazyAlertSnippetsWithButton: typeof import("../components/Alert/Snippets/WithButton.vue")['default']
export const LazyAlertSnippetsWithIcon: typeof import("../components/Alert/Snippets/WithIcon.vue")['default']
export const LazyAlertSnippetsWithLink: typeof import("../components/Alert/Snippets/WithLink.vue")['default']
export const LazyAvatarSnippetsBadge: typeof import("../components/Avatar/Snippets/Badge.vue")['default']
export const LazyAvatarSnippetsCircle: typeof import("../components/Avatar/Snippets/Circle.vue")['default']
export const LazyAvatarSnippetsColor: typeof import("../components/Avatar/Snippets/Color.vue")['default']
export const LazyAvatarSnippetsDefault: typeof import("../components/Avatar/Snippets/Default.vue")['default']
export const LazyAvatarSnippetsDropDown: typeof import("../components/Avatar/Snippets/DropDown.vue")['default']
export const LazyAvatarSnippetsGroup1: typeof import("../components/Avatar/Snippets/Group1.vue")['default']
export const LazyAvatarSnippetsGroup2: typeof import("../components/Avatar/Snippets/Group2.vue")['default']
export const LazyAvatarSnippetsInfo: typeof import("../components/Avatar/Snippets/Info.vue")['default']
export const LazyAvatarSnippetsPresence: typeof import("../components/Avatar/Snippets/Presence.vue")['default']
export const LazyAvatarSnippetsPresenceRing: typeof import("../components/Avatar/Snippets/PresenceRing.vue")['default']
export const LazyAvatarSnippetsShadow: typeof import("../components/Avatar/Snippets/Shadow.vue")['default']
export const LazyAvatarSnippetsSize: typeof import("../components/Avatar/Snippets/Size.vue")['default']
export const LazyAvatarSnippetsSquare: typeof import("../components/Avatar/Snippets/Square.vue")['default']
export const LazyBadgeSnippetsCancel: typeof import("../components/Badge/Snippets/Cancel.vue")['default']
export const LazyBadgeSnippetsDefault: typeof import("../components/Badge/Snippets/default.vue")['default']
export const LazyBadgeSnippetsIcon: typeof import("../components/Badge/Snippets/Icon.vue")['default']
export const LazyBadgeSnippetsLarge: typeof import("../components/Badge/Snippets/Large.vue")['default']
export const LazyBadgeSnippetsLink: typeof import("../components/Badge/Snippets/Link.vue")['default']
export const LazyBadgeSnippetsOutline: typeof import("../components/Badge/Snippets/Outline.vue")['default']
export const LazyBadgeSnippetsPill: typeof import("../components/Badge/Snippets/Pill.vue")['default']
export const LazyBadgeSnippetsPillOutline: typeof import("../components/Badge/Snippets/PillOutline.vue")['default']
export const LazyBadgeSnippetsPositioned: typeof import("../components/Badge/Snippets/Positioned.vue")['default']
export const LazyBadgeSnippetsRectangle: typeof import("../components/Badge/Snippets/Rectangle.vue")['default']
export const LazyBadgeSnippetsSize: typeof import("../components/Badge/Snippets/Size.vue")['default']
export const LazyBadgeSnippetsStateColor: typeof import("../components/Badge/Snippets/StateColor.vue")['default']
export const LazyBadgeSnippetsText: typeof import("../components/Badge/Snippets/Text.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
